# -*- coding: utf-8 -*-
"""lab-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n9RloUSE5xD_0q38V4jS1kjDSjujbVyA
"""

import time
print(time.ctime())

x = 1
y = 2
x
y

x = 1
y = 2
print("x = ", x)
print("y = ", y)

x = 1
y = x + 1
x = 2
y

import numpy as np
x = np.array([1, 4, 3])
x

y = np.array([[1, 4, 3], [9, 2, 7]])
y

def my_adder(a,b,c):

  out = a + b + c

  return out

my_adder(1,2,3)

help(my_adder)

def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status = 'off'
  return status

status = my_thermo_stat(65,75)
print(status)

status = my_thermo_stat(75,65)
print(status)

status = my_thermo_stat(65,63)
print(status)