# -*- coding: utf-8 -*-
"""lab-02-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ou5_mgTYAt5PyFPnq4MqB_tZ3c3KDSG
"""

import numpy as np

A = np.array([[4, 3, -5],[-2, -4, 5],[8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A,y)
print(x)

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)